#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vvis_dll'

def options(opt):
	# stub
	return

def configure(conf):
	# stub
	return

def build(bld):
	source = [
		'../common/bsplib.cpp',
		'../common/cmdlib.cpp',
		'../../public/collisionutils.cpp',
		'../../public/filesystem_helpers.cpp',
		'flow.cpp',
		'../../public/loadcmdline.cpp',
		'../../public/lumpfiles.cpp',
		'../common/mpi_stats.cpp',
		'mpivis.cpp',
		'../common/MySqlDatabase.cpp',
		'../common/pacifier.cpp',
		'../../public/scratchpad3d.cpp',
		'../common/scratchpad_helpers.cpp',
		'../common/scriplib.cpp',
		'../common/threads.cpp',
		'../common/tools_minidump.cpp',
		'../common/vmpi_tools_shared.cpp',
		'vvis.cpp',
		'WaterDist.cpp',
		'../../public/zip_utils.cpp',
		'../../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../common',
		'../vmpi',
		'../vmpi/mysql/include',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common',
	]

	defines = [
		'MPI'
    ]

	libs = [
		'tier1',
		'tier2',
		'mathlib',
		'vmpi',
		'lzma',
		'vstdlib'
    ]

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32', 'WS2_32', 'GDI32']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

