#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'lzma'

def options(opt):
	# stub
	return

def configure(conf):
    # stub
    return

def build(bld):
	source = [
        'lzma.cpp',
        'C/LzmaEnc.c',
        'C/LzmaDec.c',
        'C/LzFind.c',
    ]

	includes = [
		'.',
		'C',
		'../../public'
	]

	defines = [
		'_NO_EXCEPTIONS',
		'_LZMA_PROB32',
		'_7ZIP_ST'
    ]

	libs = [
		'tier0'
    ]

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

