#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'fgdlib'

def options(opt):
	# stub
	return

def configure(conf):
    # stub
    return

def build(bld):
	source = [
	    'gamedata.cpp',
	    'gdclass.cpp',
	    'gdvar.cpp',
	    'inputoutput.cpp',
	    'wckeyvalues.cpp',
		'../utils/common/filesystem_tools.cpp'
    ]

	includes = [
		'.',
		'../common',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../utils/common'
	]

	defines = []
	libs = [
		'tier0',
		'tier1'
    ]

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

