#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'shadercompile'

def options(opt):
    # stub
    return

def configure(conf):
    return

def build(bld):
    if bld.env.DEST_OS == 'android':
        return

    source = ['shadercompile_launcher.cpp']
    includes = [
        '../../public',
        '../../public/tier1'
    ]
    defines = []
    libs = [
        'tier0',
        'tier1',
        'vstdlib',
        'USER32',
        'SHELL32'
    ]

    linkflags = []

    if bld.env.DEST_OS == 'win32':
        linkflags += [
            '/SUBSYSTEM:CONSOLE'
        ]

    install_path = bld.env.LIBDIR
    bld(
        source   = source,
        target   = PROJECT_NAME,
        name     = PROJECT_NAME,
        features = 'c cxx cxxprogram',
        includes = includes,
        defines  = defines,
        use      = libs,
        linkflags = linkflags,
        install_path = install_path,
        subsystem = bld.env.MSVC_SUBSYSTEM,
        idx      = bld.get_taskgen_count()
    )

