#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'stdshader_dx11'

def options(opt):
	# stub
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'STDSHADER_DX11_DLL_EXPORT',
		'FAST_MATERIALVAR_ACCESS'
	])

def build(bld):
	stdshader_dx11_50 = [
		'bik_vs50.fxc',
		'bik_ps50.fxc',
		'unlitgeneric_vs50.fxc',
		'unlitgeneric_ps50.fxc',
		'white_ps50.fxc',
		'writez_vs50.fxc',
		'modulate_ps50.fxc',
		'modulate_vs50.fxc',
		'splinecard_vs50.fxc',
		'spritecard_vs50.fxc',
		'spritecard_ps50.fxc',
		'sprite_ps50.fxc',
		'sprite_vs50.fxc',
		'sky_vs50.fxc',
		'sky_ps50.fxc',
		'sky_hdr_compressed_rgbs_ps50.fxc',
		'sky_hdr_compressed_ps50.fxc',
		'decalmodulate_ps50.fxc',
		'vertexlit_and_unlit_generic_vs50.fxc',
		'vertexlit_and_unlit_generic_ps50.fxc',
		'depthtodestalpha_vs50.fxc',
		'depthtodestalpha_ps50.fxc',
		'wireframe_ps50.fxc',
		'wireframe_vs50.fxc',
		'lightmappedgeneric_ps50.fxc',
		'lightmappedgeneric_vs50.fxc',
		'lightmappedgeneric_flashlight_ps50.fxc',
		'lightmappedgeneric_flashlight_vs50.fxc',
		'unlittwotexture_ps50.fxc',
		'unlittwotexture_vs50.fxc',
		'shadow_ps50.fxc',
		'shadow_vs50.fxc',
		'shadowmodel_ps50.fxc',
		'shadowmodel_vs50.fxc',
		'depthwrite_ps50.fxc',
		'depthwrite_vs50.fxc'
	]
	bld(
		source = stdshader_dx11_50,
		target = 'stdshader_dx11_50',
		features = 'fxc',
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

	source = [
		'BaseVSShader.cpp' ,
		'bik_dx11.cpp',
		'modulate_dx11.cpp',
		'occlusion_dx11.cpp',
		'test_dx11.cpp',
		'unlitgeneric_dx11.cpp',
		'wireframe_dx11.cpp',
		'writez_dx11.cpp',
		'vertexlitgeneric_dx11.cpp',
		'vertexlitgeneric_dx11_helper.cpp',
		'lightmappedgeneric_dx11.cpp',
		'lightmappedgeneric_dx11_helper.cpp',
		'unlittwotexture_dx11.cpp',
		'decalmodulate_dx11.cpp',
		'sprite_dx11.cpp',
		'spritecard_dx11.cpp',
		'sky_dx11.cpp',
		'sky_hdr_dx11.cpp',
		'worldvertextransition_dx11.cpp',
		'shadow_dx11.cpp',
		'shadowmodel_dx11.cpp',
		'depthwrite_dx11.cpp',
		'../shader_dll_verify.cpp',
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'fxctmp9',
		'vshtmp9'
	] + bld.env.INCLUDES_SDL2

	defines = [
		'SHADERLIB_DX11'
	]

	libs = [
		'tier0',
		'tier1',
		'mathlib',
		'shaderlib_dx11'
	]

	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

