#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils

top = '.'
PROJECT_NAME = 'luainterface'

def options(opt):
	# stub
	return

def configure(conf):
	#stub
	return

def build(bld):
	source = [
		'luainterface.cpp',
		'luastate.cpp',
		'luacommon.cpp',
		#'../public/tier0/memoverride.cpp'
	]
	source = source + bld.path.ant_glob('libraries/*.cpp')
	source.append('../public/tier0/memoverride.cpp')

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common',
		'../thirdparty/luajit/include',
	]

	defines = []

	libs = ['tier0','vpklib','tier1','tier2','vstdlib','LUAJIT']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)